name: Build
on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: secondlife/action-autobuild@v3
        with:
          platform: common
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v3
